environment_version: 1
credentials:
- type: general
  id: f5VqP51TGMLOyiuG
  description: CODEOCEAN_DOMAIN
  value: CODEOCEAN_DOMAIN
- type: general
  id: 01IOr2PnQmjXXOpX
  description: CODEOCEAN_API_TOKEN
  value: CODEOCEAN_API_TOKEN
